services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: scada_demo_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosq_data:/mosquitto/data
      - mosq_log:/mosquitto/log
volumes:
  mosq_data: {}
  mosq_log: {}
